# Form implementation generated from reading ui file 'dangky.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import hashlib
import re
import sqlite3


class Ui_DangKy(object):
    def setupUi(self, DangKy):
        DangKy.setObjectName("DangKy")
        DangKy.resize(595, 600)
        self.centralwidget = QtWidgets.QWidget(parent=DangKy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 230, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 325, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 380, 351, 81))
        self.label_5.setObjectName("label_5")
        self.cbDieuKhoan = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.cbDieuKhoan.setGeometry(QtCore.QRect(100, 460, 291, 20))
        self.cbDieuKhoan.setObjectName("cbDieuKhoan")
        self.btnDangKy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDangKy.setGeometry(QtCore.QRect(220, 500, 131, 28))
        self.btnDangKy.setObjectName("btnDangKy")
        self.rbNam = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rbNam.setGeometry(QtCore.QRect(100, 370, 95, 20))
        self.rbNam.setObjectName("rbNam")
        self.rbNu = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rbNu.setGeometry(QtCore.QRect(230, 370, 95, 20))
        self.rbNu.setObjectName("rbNu")
        self.rbTuychinh = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rbTuychinh.setGeometry(QtCore.QRect(360, 370, 95, 20))
        self.rbTuychinh.setObjectName("rbTuychinh")
        self.txtHo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtHo.setGeometry(QtCore.QRect(100, 130, 141, 22))
        self.txtHo.setObjectName("txtHo")
        self.txtSDTEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSDTEmail.setGeometry(QtCore.QRect(100, 170, 331, 22))
        self.txtSDTEmail.setObjectName("txtSDTEmail")
        self.txtTen = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTen.setGeometry(QtCore.QRect(290, 130, 141, 22))
        self.txtTen.setObjectName("txtTen")
        self.txtMatkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMatkhau.setGeometry(QtCore.QRect(100, 210, 331, 22))
        self.txtMatkhau.setObjectName("txtMatkhau")
        self.cbNgay = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbNgay.setGeometry(QtCore.QRect(100, 280, 73, 22))
        self.cbNgay.setCurrentText("")
        self.cbNgay.setObjectName("cbNgay")
        self.cbThang = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbThang.setGeometry(QtCore.QRect(200, 280, 103, 22))
        self.cbThang.setObjectName("cbThang")
        self.cbNam = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbNam.setGeometry(QtCore.QRect(350, 280, 100, 22))
        self.cbNam.setObjectName("cbNam")
        DangKy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DangKy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 26))
        self.menubar.setObjectName("menubar")
        DangKy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DangKy)
        self.statusbar.setObjectName("statusbar")
        DangKy.setStatusBar(self.statusbar)

        self.retranslateUi(DangKy)
        self._init_birth_fields()
        self.txtMatkhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.btnDangKy.clicked.connect(self.handle_register)
        QtCore.QMetaObject.connectSlotsByName(DangKy)

    def _init_birth_fields(self):
        self.cbNgay.clear()
        self.cbThang.clear()
        self.cbNam.clear()

        self.cbNgay.addItems([str(day) for day in range(1, 32)])
        self.cbThang.addItems([f"Tháng {month}" for month in range(1, 13)])

        current_year = QtCore.QDate.currentDate().year()
        self.cbNam.addItems([str(year) for year in range(current_year, 1949, -1)])

    def _get_gender(self):
        if self.rbNam.isChecked():
            return "Nam"
        if self.rbNu.isChecked():
            return "Nữ"
        if self.rbTuychinh.isChecked():
            return "Tùy chỉnh"
        return ""

    def _validate_password(self, password):
        if len(password) < 8:
            return False
        if not re.search(r"[a-z]", password):
            return False
        if not re.search(r"[A-Z]", password):
            return False
        if not re.search(r"\d", password):
            return False
        if not re.search(r"[^a-zA-Z0-9]", password):
            return False
        return True

    def _validate_contact(self, contact):
        email_pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"
        phone_pattern = r"^\+?\d{9,11}$"
        return bool(re.match(email_pattern, contact) or re.match(phone_pattern, contact))

    def _hash_password(self, password):
        return hashlib.sha256(password.encode("utf-8")).hexdigest()

    def _save_to_database(self, data):
        conn = sqlite3.connect("dangky.db")
        cursor = conn.cursor()

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ho TEXT NOT NULL,
                ten TEXT NOT NULL,
                sdt_email TEXT NOT NULL,
                mat_khau_hash TEXT NOT NULL,
                ngay_sinh TEXT NOT NULL,
                gioi_tinh TEXT NOT NULL,
                dong_y_dieu_khoan INTEGER NOT NULL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        cursor.execute(
            """
            INSERT INTO users (
                ho, ten, sdt_email, mat_khau_hash, ngay_sinh, gioi_tinh, dong_y_dieu_khoan
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                data["ho"],
                data["ten"],
                data["sdt_email"],
                data["mat_khau_hash"],
                data["ngay_sinh"],
                data["gioi_tinh"],
                1,
            ),
        )

        conn.commit()
        conn.close()

    def _clear_form(self):
        self.txtHo.clear()
        self.txtTen.clear()
        self.txtSDTEmail.clear()
        self.txtMatkhau.clear()
        self.cbNgay.setCurrentIndex(0)
        self.cbThang.setCurrentIndex(0)
        self.cbNam.setCurrentIndex(0)
        self.rbNam.setAutoExclusive(False)
        self.rbNu.setAutoExclusive(False)
        self.rbTuychinh.setAutoExclusive(False)
        self.rbNam.setChecked(False)
        self.rbNu.setChecked(False)
        self.rbTuychinh.setChecked(False)
        self.rbNam.setAutoExclusive(True)
        self.rbNu.setAutoExclusive(True)
        self.rbTuychinh.setAutoExclusive(True)
        self.cbDieuKhoan.setChecked(False)

    def handle_register(self):
        ho = self.txtHo.text().strip()
        ten = self.txtTen.text().strip()
        sdt_email = self.txtSDTEmail.text().strip()
        mat_khau = self.txtMatkhau.text()
        gioi_tinh = self._get_gender()

        errors = []
        if not ho:
            errors.append("- Họ là bắt buộc.")
        if not ten:
            errors.append("- Tên là bắt buộc.")
        if not sdt_email:
            errors.append("- Số điện thoại hoặc email là bắt buộc.")
        if not mat_khau:
            errors.append("- Mật khẩu là bắt buộc.")

        if sdt_email and not self._validate_contact(sdt_email):
            errors.append("- Số điện thoại hoặc email không đúng định dạng.")

        if mat_khau and not self._validate_password(mat_khau):
            errors.append(
                "- Mật khẩu phải có ít nhất 8 ký tự, gồm chữ thường, chữ hoa, số và ký tự đặc biệt."
            )

        if not gioi_tinh:
            errors.append("- Bạn phải chọn giới tính.")

        if not self.cbDieuKhoan.isChecked():
            errors.append("- Bạn phải xác nhận đồng ý với các điều khoản.")

        if errors:
            QtWidgets.QMessageBox.warning(None, "Thông báo", "\n".join(errors))
            return

        data = {
            "ho": ho,
            "ten": ten,
            "sdt_email": sdt_email,
            "mat_khau_hash": self._hash_password(mat_khau),
            "ngay_sinh": f"{self.cbNgay.currentText()}/{self.cbThang.currentIndex() + 1}/{self.cbNam.currentText()}",
            "gioi_tinh": gioi_tinh,
        }

        try:
            self._save_to_database(data)
            QtWidgets.QMessageBox.information(None, "Thành công", "Đăng ký thành công.")
            self._clear_form()
        except Exception as exc:
            QtWidgets.QMessageBox.critical(None, "Lỗi", f"Không thể lưu dữ liệu: {exc}")

    def retranslateUi(self, DangKy):
        _translate = QtCore.QCoreApplication.translate
        DangKy.setWindowTitle(_translate("DangKy", "MainWindow"))
        self.label.setText(_translate("DangKy", "<html><head/><body><p>Đăng ký</p></body></html>"))
        self.label_2.setText(_translate("DangKy", "Nhanh chóng  và dễ dàng"))
        self.label_3.setText(_translate("DangKy", "Ngày sinh"))
        self.label_4.setText(_translate("DangKy", "Giới tính"))
        self.label_5.setText(_translate("DangKy", "Bằng cách nhấp vào Đăng ký, bạn đồng ý với Điều khoản,\n"
"Chính sách dữ liệu và Chính sách cookie của chúng tôi. Bạn có\n"
"thể nhận được thông báo của chúng tôi qua SMS và hủy nhận\n"
"bất kỳ lúc nào."))
        self.cbDieuKhoan.setText(_translate("DangKy", "Tôi đồng ý với các điều khoản trên"))
        self.btnDangKy.setText(_translate("DangKy", "Đăng ký"))
        self.rbNam.setText(_translate("DangKy", "Nam"))
        self.rbNu.setText(_translate("DangKy", "Nữ"))
        self.rbTuychinh.setText(_translate("DangKy", "Tuỳ chinh"))
        self.txtHo.setPlaceholderText(_translate("DangKy", "Họ"))
        self.txtSDTEmail.setPlaceholderText(_translate("DangKy", "Số di động hoặc email"))
        self.txtTen.setPlaceholderText(_translate("DangKy", "Tên"))
        self.txtMatkhau.setPlaceholderText(_translate("DangKy", "Mật khẩu mới"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DangKy = QtWidgets.QMainWindow()
    ui = Ui_DangKy()
    ui.setupUi(DangKy)
    DangKy.show()
    sys.exit(app.exec())
