# Form implementation generated from reading ui file 'QT design/tinhtong.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 120, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 200, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txtNumber1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtNumber1.setGeometry(QtCore.QRect(240, 110, 301, 31))
        self.txtNumber1.setObjectName("txtNumber1")
        self.txtNumber2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtNumber2.setGeometry(QtCore.QRect(240, 190, 301, 31))
        self.txtNumber2.setObjectName("txtNumber2")
        self.sum = QtWidgets.QLabel(parent=self.centralwidget)
        self.sum.setGeometry(QtCore.QRect(150, 290, 55, 16))
        self.sum.setObjectName("sum")
        self.btnSum = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSum.setGeometry(QtCore.QRect(240, 240, 301, 28))
        self.btnSum.setObjectName("btnSum")
        self.txtSum = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtSum.setGeometry(QtCore.QRect(240, 290, 301, 31))
        self.txtSum.setObjectName("txtSum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnSum.clicked.connect(self.calculate_sum)
        self.txtSum.setReadOnly(True)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def calculate_sum(self):
        try:
            number1 = float(self.txtNumber1.toPlainText().strip())
            number2 = float(self.txtNumber2.toPlainText().strip())
            total = number1 + number2

            # Hide trailing .0 for integer values.
            if total.is_integer():
                self.txtSum.setPlainText(str(int(total)))
            else:
                self.txtSum.setPlainText(str(total))
        except ValueError:
            QtWidgets.QMessageBox.warning(
                None,
                "Input Error",
                "Please enter valid numbers in Number 1 and Number 2.",
            )
            self.txtSum.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EAUT"))
        self.label.setText(_translate("MainWindow", "Number 1"))
        self.label_2.setText(_translate("MainWindow", "Number 2"))
        self.sum.setText(_translate("MainWindow", "Sum"))
        self.btnSum.setText(_translate("MainWindow", "Sum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
